mysite/chat/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView


app_name = 'chat'
urlpatterns = [
    path('', views.registration_page, name='registration_page'),
    path('userpage/<int:user_id>/', views.user_page, name='userpage'),
    path(
        'login/',
        LoginView.as_view(template_name='chat/log-in.html'),
        name='login',
         ),
]

mysite/mysite/urls.py
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib import admin
from django.conf import settings


urlpatterns = [
    path('', include('chat.urls', namespace='mysite-chat')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/chat/models.py
from django.contrib.auth.models import User
from django.db import models
from django.conf import settings
from django.db.models.signals import post_save
from django.dispatch import receiver
# Create your models here.


class UserAccount(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, primary_key=True)
    user_photo = models.ImageField(upload_to='userphoto/')


@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        UserAccount.objects.create(user=instance)


@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def save_user_profile(sender, instance, **kwargs):
    instance.useraccount.save()

mysite/chat/forms.py
from .models import UserAccount, User
from django.contrib.auth.forms import UserCreationForm
from django.forms import ModelForm


class RegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        super(UserCreationForm, self).__init__(*args, **kwargs)

        for fieldname in ['username', 'password1', 'password2']:
            self.fields[fieldname].help_text = None


class UserPageForm(ModelForm):
    class Meta:
        model = UserAccount
        fields = ('user_photo',)

mysite/chat/views.py
from django.shortcuts import render, redirect
from .forms import RegistrationForm, UserPageForm
from django.contrib.auth import authenticate, login, logout
from . import models


def registration_page(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)

        if form.is_valid():
            form.save()
            # Username and password should be received at raw form
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            # Logs in the user for current session
            user = authenticate(request, username=username, password=raw_password)
            login(request, user)
            # First_name by default
            def_fname = request.user
            def_fname.first_name = 'unknown'
            def_fname.save()

            return redirect('/userpage/' + str(request.user.id))
    # Whether user have authenticated already
    elif request.user.is_authenticated:

        return redirect('/userpage/' + str(request.user.id))
    # Blank form have been passed
    else:
        form = RegistrationForm()

    users_names = models.UserAccount.objects.all()

    return render(request, 'chat/register_page.html', {'form': form, 'users_names': users_names})


def user_page(request, user_id):
    #  change photo
    if request.method == 'POST' and request.FILES['user_photo']:
        form = UserPageForm(request.POST, request.FILES, instance=request.user.useraccount)

        if form.is_valid():
            form.save()

            return redirect('/userpage/' + str(request.user.id))
        else:

            return render(request, 'chat/userpage.html', {'form': form, 'user_id': user_id})
    #  logout user condition
    if 'logout' in request.GET:
        logout(request)

        return redirect('/login/')
    # Check for whether existing user page.
    if models.UserAccount.objects.get(user=user_id):
        url_photo = models.UserAccount.objects.get(user=user_id)

        return render(request, 'chat/userpage.html', {'user_id': user_id, 'url_photo': url_photo})

mysite/chat/templates/chat/log-in.html
{% extends "chat/register_page.html" %}
{% block title %}
    <title>Log-in page</title>
{% endblock %}
{% block body %}
<div class="container col-xs-4 col-sm-4 col-md-4 col-lg-4 col-xl-6">
    <div class="row">
        <div class="col col-xs-6 col-sm-6 col-md-6 col-lg-6 col-xl-9 rounded" style="padding: 20px;margin:100px; background: rgba(255, 153, 51, 0.7)" >
            <h2 class="text-center display-4" style="color: #5cb85c;">Log-in page</h2>
            <hr>
            <form action="" method="post">
                {% csrf_token %}
                {% if form.errors %}
                <div class="alert alert-danger">{{ form.errors }}</div>
                {% endif %}
                <input type="text" placeholder="Enter the username" class="form-control" name="username" maxlength="120" required id="id_username">
                <br>
                <input type="password" placeholder="Enter the password" class="form-control" name="password" required id="id_password">
                <br>
                <button type="submit" class="btn btn-block" style="background: #5cb85c; font-family: 'Titillium Web', sans-serif; font-size: 20px; color: rgba(255, 153, 51, 0.7)" >Log-in</button>
                <br>
                <div class="row" style="float: right;">
                    <label class="text" style="font-family: 'Titillium Web', sans-serif;color: #f2f2f2;">Don't have a one?</label>
                    <a href="{% url 'chat:registration_page' %}" style="font-family: 'Titillium Web', sans-serif;">Registration</a>
                </div>
            </form >
        </div>
    </div>
</div>
{% endblock %}

mysite/chat/templates/chat/register_page.html
{% load static %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head lang="en-US">
  <meta charset="utf-8" />
  <!-- For mobile devises -->
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
{% block title %}
  <title>Registration page</title>
{% endblock %}
<link rel="stylesheet" href="{% static 'chat/bg_video.css' %}" />
<link rel="stylesheet" href="{% static 'chat/reg_page.css' %}" />
<link href="https://fonts.googleapis.com/css?family=Nunito+Sans" rel="stylesheet" />
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
<![endif]-->
</head>
<body>
  <div class="fullscreen-bg">
        <video autoplay="" loop="" poster="" class="fullscreen-bg__video" src="http://static.videezy.com/system/resources/previews/000/000/328/original/bokeh2.mp4">
        </video>
  </div>
{% block body %}
<!-- main section (registration table) -->
  <section class="reg_table">
    <div class="reg_table">
      <table style="width: 100%;">
        <caption>Registration</caption>
        <tbody>
          <form action="" method="post">
            {% csrf_token %}
            <tr>
              <td>
                {% if form.username.errors %}
                <span>{{ form.username.errors }}</span>
                {% endif %}
                <input type="text" placeholder="Enter username" name="username" maxlength="150" required="required" id="id_username" />
              </td>
            </tr>
            <tr>
              <td>
                <input type="password" placeholder="Enter password" name="password1" required="required" id="id_password1" />
              </td>
            </tr>
            <tr>
              <td>
                {% if form.password2.errors %}
                <span>{{ form.password2.errors }}</span>
                {% endif %}
                <input type="password" placeholder="Enter password again" name="password2" required="required" id="id_password2" />
              </td>
            </tr>
            <tr>
              <td>
                <input type="email" placeholder="Enter email" name="email" required="required" id="id_email" />
              </td>
            </tr>
            <tr>
              <td class="sub_form_td" style="display: flex; justify-content: center;">
                <input type="submit" value="Sign up" />
                <a href="{% url 'chat:login' %}">or to login</a>
              </td>
            </tr>
            </form>
        </tbody>
      </table>
    </div>
     <!-- displaying all registered users -->
    <div class="disp_all_users">
      {% for username in users_names %}
      <a href="/userpage/{{ username.user.id }}">{{ username.user.first_name }}</a>  
      {% endfor %}
    </div>
  </section>
{% endblock %}
</body>
</html>

mysite/chat/templates/chat/userpage.html
{% extends "chat/register_page.html" %}
{% load static %}
{% block title %}
    <title>User page</title>
{% endblock %}
{% block body %}
{% if user.is_authenticated %}
<nav class="navbar sticky-top " style=" background:rgba(255, 153, 51, 0.8);">
    <div class="dropdown">
        <button class="btn  dropdown-toggle" style="background:rgba(255, 153, 51, 0.1)" type="button" id="dropdownMenuButton" aria-haspopup="true" aria-expanded="false" data-toggle="dropdown">Menu</button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <form action="" method="get">
                <input type="submit" class="dropdown-item" value="Log-out" name="logout">
            </form>
        </div>
    </div>
</nav>
{% endif %}
<div class="container col-xs-4 col-sm-4 col-md-4 col-lg-4 col-xl-4">
    <div class="row-center">
        <div class="col col-xs-6 col-sm-6 col-md-6 col-lg-6 col-xl-11 rounded" style="background:rgba(255, 153, 51, 0.8);padding:1px;margin:10px">
            <form enctype="multipart/form-data" method="post" class="">
            {% csrf_token %}
                <label class="btn">
                    {% if url_photo.user_photo %}
                    <img src="{{ url_photo.user_photo.url }}" class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 image-fluid" style="padding: 0px">
                    {% else %}
                    <img src="{% static 'chat/user_photo.jpg' %}" alt="photo not found" class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 image-fluid">
                    {% endif %}
                    {% if user.is_authenticated %}
                    <input type="file" name="user_photo" id="id_user_photo" required="" hidden>
                    <button class="btn btn-block" type="submit">send</button>
                    {% endif %}

                </label>
            </form>
            <a class="btn btn-block" data-toggle="collapse" data-target="#about" style="font: icon" >About me<span class="caret"></span></a>
            <div id="about" class="collapse"><ul><li>{{ user.first_name }}</li><li>{{ user.last_name }}</li><li>summery</li></ul></div>
            <a class="btn btn-block" data-toggle="collapse" data-target="#contacts" style="font: icon" >Contacts<span class="caret"></span></a>
            <div id="contacts" class="collapse"><ul><li>Phone</li><li>Web messanger</li><li>{{ user.email_address }}</li></ul></div>
        </div>
    </div>
</div>
{% endblock %}